apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
      - image: cassandra
        name: cassandra
        ports:
        - name: cassandra
          containerPort: 9042
          hostPort: 9042
        volumeMounts:
            - name: cassandra-storage
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-storage
          gcePersistentDisk:
            pdName: realty-cassandra4
            fsType: ext4
