apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: elastic
  name: elastic-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elastic
    spec:
      containers:
      - image: oslick/elastic
        name: elastic
        ports:
        - name: elastic
          containerPort: 9200
          hostPort: 9200
