apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: elastic
  name: elastic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elastic
    spec:
      containers:
      - image: oslick/elastic
        name: elastic
        ports:
        - name: elastic
          containerPort: 9200
          hostPort: 9200
        volumeMounts:
            - name: elastic-storage
              mountPath: /data
      volumes:
        - name: elastic-storage
          gcePersistentDisk:
            pdName: realty-elastic
            fsType: ext4
      resources:
         requests:
          cpu: "250m"
         limits:
          cpu: "300m"