apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
         containers:
         - image: gcr.io/realty3-2016/nginx:v8
           name: nginx
           ports:
           - containerPort: 80
             hostPort: 80
             name: nginx
