apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: node
  name: node-controller
spec:
  replicas: 1
  selector:
    name: node
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
      - image: oslick/node:8acce315762734875d22ba5e6417751eab6c305e
        name: node
        ports:
        - containerPort: 8000
          hostPort: 8000
          name: node
