apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: repar
  name: repar
spec:
  replicas: 2
  selector:
    name: repar
  template:
    metadata:
      labels:
        name: repar
    spec:
      containers:
      - image: gcr.io/realty3-2016/repar:v1
        name: repar
        ports:
        - containerPort: 4444
          hostPort: 4444
          name: repar
