apiVersion: v1
kind: Service
metadata:
  name: repar
  labels:
    name: repar
spec:
  type: LoadBalancer
  ports:
    - port: 4444 
      targetPort: 4444
      protocol: TCP
  selector:
    name: repar
