apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: varnish
  name: varnish
spec:
  replicas: 1
  selector:
    name: varnish
  template:
    metadata:
      labels:
        name: varnish
    spec:
         containers:
         - image: gcr.io/realty3-2016/varnish:v1
           name: varnish
           ports:
           - containerPort: 80
             hostPort: 80
             name: varnish
           resources:
             request:
               cpu: 50
